services:
  app:
    build:
      dockerfile: development.Dockerfile
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: entrypoint.sh
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 'restaurants_development'

  sidekiq:
    build:
      dockerfile: development.Dockerfile
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7.0.7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: