development:
  adapter: async
  url: "redis://redis:6379/1"
  channel_prefix: restaurant_development

test:
  adapter: test

production:
  adapter: redis
  url: "redis://redis:6379/1"
  channel_prefix: restaurant_production
